### ISSUE TITLE
Error when validating mail (id="email--1") and error with selenium( DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by Porkechebure** [dimakiss/Udemy_bot#10]
As mentioned I tried to run the bot in a docker container, which is equal on running it in a linux environment.
I will avoid to tell you the hell I had to do to make this bot work. I Cried long hours and pulled my hair in every way. Believe me.
In the end, I managed to do it but I got this:

> Checking if the email and password are correct
> Traceback (most recent call last):
>   File "/etc/udemybot/Udemy_bot.py", line 203, in <module>
>     elif is_account_exist(sys.argv[1], sys.argv[2]):
>   File "/etc/udemybot/Udemy_bot.py", line 182, in is_account_exist
>     browser = webdriver.Chrome(options=options)
>   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
>     RemoteWebDriver.__init__(
>   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
>   (unknown error: DevToolsActivePort file doesn't exist)
>   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

The only way I found to workaround this is to add in the code

   ```
 print("Checking if the email and password are correct")
    options = Options()
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--incognito")
    options.add_argument("--headless")
```
Have you got a better solution?

Then, after fixing this with a clunky workaround, I get this:

> Checking if the email and password are correct
> Traceback (most recent call last):
>   File "/etc/udemybot/Udemy_bot.py", line 203, in <module>
>     elif is_account_exist(sys.argv[1], sys.argv[2]):
>   File "/etc/udemybot/Udemy_bot.py", line 186, in is_account_exist
>     browser.find_element_by_id("email--1").send_keys(email)
>   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
>     return self.find_element(by=By.ID, value=id_)
>   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
>     return self.execute(Command.FIND_ELEMENT, {
>   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="email--1"]"}
>   (Session info: headless chrome=88.0.4324.150)

What can it be? I know it's the html parser that is missing something  but debugging in the container it's hard.
You have any idea of what's going on?

EDIT: I printed the html with
`print(browser.page_source)`

And what you get is this:

`<div aria-hidden="true" style="background-color: rgb(255, 255, 255); border: 1px solid rgb(208, 208, 208); box-shadow: rgba(0, 0, 0, 0.1) 0px 0px 4px; border-radius: 4px; left: -10000px; top: -10000px; z-index: -2147483648; position: absolute; transition: opacity 0.15s ease-out 0s; opacity: 0; visibility: hidden;"><div style="position: relative;"><iframe src="https://assets.hcaptcha.com/captcha/v1/40446ab/static/hcaptcha-challenge.html#id=0lcxfl97hd5&amp;host=www.udemy.com&amp;sentry=true&amp;reportapi=https%3A%2F%2Faccounts.hcaptcha.com&amp;recaptchacompat=off&amp;sitekey=33f96e6a-38cd-421b-bb68-7806e1764460" title="Main content of the hCaptcha challenge" frameborder="0" scrolling="no" style="border: 0px; z-index: 2000000000; position: relative;"></iframe></div><div style="width: 100%; height: 100%; position: fixed; pointer-events: none; top: 0px; left: 0px; z-index: 0; background-color: rgb(255, 255, 255); opacity: 0.05;"></div><div style="border-width: 11px; position: absolute; pointer-events: none; margin-top: -11px; z-index: 1; right: 100%;"><div style="border-width: 10px; border-style: solid; border-color: transparent rgb(255, 255, 255) transparent transparent; position: relative; top: 10px; z-index: 1;"></div><div style="border-width: 11px; border-style: solid; border-color: transparent rgb(208, 208, 208) transparent transparent; position: relative; top: -11px; z-index: 0;"></div></div></div></body></html>`

Which looks like some bot protection measure from [https://www.botstop.com/?utm_source=hcaptcha1](https://www.botstop.com/?utm_source=hcaptcha1) or something like that

Any idea?

**Comment by Porkechebure** [comment]
So, apparently, you gotta add some more arguments with 
`options.add_argument`

which are user-agent, accept-language and others to not appear as a bot to udemy and it works.
